export const secondQ = [
  "Definicja przedsiębiorstwa (1,2)",
  "Wyodrębnienie prawne ",
  "Podmiotowość prawna ",
  "Osobowość prawna ",
  "Podejście podmiotowe do przedsiębiorstwa ",
  "Podejście przedmiotowe do przedsiębiorstwa ",
  "Podejście funk",
  "Atrybuty przedsiębiorstwa (11)",
  "Autonomia przedsiębiorstwa",
  "Zasady działania przedsiębiorstw",
  "Przejawy autonomii przedsiębiorstwa",
  "Zasada optymalnego kształtowania zależności między czynnikami produkcji",
  "Zasada gospodarności",
  "Zasada przedsiębiorczości ",
  "Zasada rentowności ",
  "Zasada konkurencyjności ",
  "Ewolucja przedsiębiorstwa",
  "Cykl życia przedsiębiorstwa",
  "Faza utworzenia przedsiębiorstwa ",
  "Faza rozwoju przedsiębiorstwa ",
  "Faza dojrzałości przedsiębiorstwa ",
  "Faza schyłku przedsiębiorstwa ",
  "Faza zaprzestania działalności przedsiębiorstwa ",
  "Czynniki długowieczności ",
  "Cykl życia a restrukturyzacja",
  "Restrukturyzacja - definicje ",
  "Cele restrukturyzacji ",
  "Cele uwarunkowania ",
  "Bariery restrukturyzacji ",
  "Podstawowe rodzaje restrukturyzacji ",
  "Naprawcza restrukturyzacja ",
  "Dostosowawcza restrukturyzacja ",
  "Antycypacyjna restrukturyzacja ",
  "Kreatywna restrukturyzacji ",
  "Charakterystyka restrukturyzacji",
  "Podstawowe rodzaje restrukturyzacji ",
  "Rodzaje restrukturyzacji",
  "Typologia przedsiębiorstw",
  "Użyteczność klasyfikowania przedsiębiorstw ",
  "Wybrane kryteria klasyfikacji przedsiębiorstw ",
  "Cel działalności gospodarczej",
  "Forma własności kapitału ",
  "Forma organizacyjno-prawna przedsiębiorstwa",
  "Liczba właścicieli przedsiębiorstwa",
  "Wielkość przedsiębiorstwa",
  "Rodzaj zintegrowania przesiębiorstwa",
  "Zakres internacjonalizacji ",
  "Problemy współczesne przedsiębiorstw ",
  "Procesy decyzyjne przedsiębiorstw w momencie problemu ",
  "Wewnętrzne źródła problemów przedsiębiorstw",
  "Zewnętrzne źródła problemów przedsiębiorstw ",
  "Interesariusze przedsiębiorstwa - definicja ",
  "Interesariusze - podmioty",
  "Interesariusze a cele",
  "Misja przedsiębiorstwa - definicja ",
  "Kategorie celowościowe ",
  "Cel przedsiębiorstwa - definicja ",
  "Sposoby rozumienia celu",
  "Funkcje celów",
  "Hierarchia celów",
  "Podstawowy podział celów ",
  "Cele podstawowe przedsiębiorstw ",
  "Cele cząstkowe przedsiębiorstw wewnętrzne",
  "Cele cząstkowe przedsiębiorstw zewnętrzne ",
  "Cele stopniowalne",
  "Cele niestopniowalne ",
  "Cele końcowe",
  "Cele pośrednie",
  "Cele oficjalne",
  "Cele operacyjne ",
  "Cele formalne",
  "Cele nieformalne",
  "Sposoby postrzegania przedsiębiorstwa (2)",
  "Nauka o przedsiębiorstwie - definicja",
  "Podział nauki o przedsiębiorstwie ",
  "Fazy tworzenia nauki o przedsiębiorstwie ",
  "Ewolucja teorii przedsiębiorstw ",
];

export const firstQ = [
  "Ekonomika przedsiębiorstwa ",
  "Aspekty ekonomiki przedsiębiorstwa ",
  "Bilans ",
  "Rachunek zysków i strat ",
  "Rachunek przepływów pieniężnych",
  "Wpływ finansowy",
  "Przychód",
  "Wydatek",
  "Koszt ",
  "Wydatek a koszt ",
  "Koszt własny przedsiębiorstwa ",
  "Nakład ",
  "Układ kosztów (2)",
  "Ustalenie wyniku ",
  "Wynik działalności netto",
  "Wynik działalności brutto",
  "Wynik działalności  z działalności operacyjnej ",
  "Wynik działalności ze sprzedaży",
  "Wynik działalności brutto ze sprzedaży",
  "Ustalenie wyniku ",
];
